var _devaneios = [101, 102,108,110]; 
var _finais = [100, 107, 106, 104, 105, 103,109,111];



tocar(snd_final_ok)
tocar(snd_final_bom)



global.devaneio = false;
room_destino = Rm_variaveis;
linhas = [];
is_sobre = false;
var _nome = "";
global.deslocar=0


if (global.historia == 101) {
    _nome = "A GAROTA ESTABANADA";
    global.devaneio = true;
    room_destino = Rm_Alem_dia_0;
    linhas = [
        "O ACIDENTE NO ESCURO COBROU O SEU PREÇO. O SANGUE DE ELLIE\nMANCHOU AS MÃOS DE TIFFANY PARA SEMPRE.",
        "A CULPA A CONSUMIU. ELA SE ENTREGOU À POLÍCIA NAQUELA MESMA NOITE,\nINCAPAZ DE CONVIVER COM O PESO DA PRÓPRIA TRAGÉDIA.",
        "DOMINÓ, ESCONDIDO NAS SOMBRAS, APENAS ASSISTIU AO DESESPERO.\nELE FALHOU EM IMPEDIR O PIOR, SENDO O ARQUITETO SILENCIOSO DO CAOS.",
        "ATORMENTADO PELAS MÚLTIPLAS REALIDADES, O DETETIVE ABANDONOU O CASO\nE FUGIU PARA O LIMBO, BUSCANDO UMA FORMA DE CONSERTAR SEUS ERROS."
    ];
} 
else if (global.historia == 102) {
    _nome = "A ILUSÃO DO DETETIVE";
    global.devaneio = true;
    room_destino = Rm_Alem_dia_0;
    linhas = [
        "A SALA DO LIMBO DESAPARECE, DANDO LUGAR A PAREDES BRANCAS E ACOLCHOADAS.\nA REALIDADE VEM À TONA: O 'DETETIVE' USA UMA CAMISA DE FORÇA.",
        "ELLIE É SUA MÉDICA. TIFFANY, SUA TERAPEUTA. BRENO, UM DOS GUARDAS.\nTHEO OBSERVA PELAS CÂMERAS E SAM É APENAS SEU COLEGA DE ALOJAMENTO.",
        "NÃO HÁ CASO, NÃO HÁ PARADOXO. APENAS UM HOMEM PRESO EM SEUS DELÍRIOS,\nFUGINDO DA CULPA DE UM CRIME REAL QUE SUA MENTE SE RECUSA A ACEITAR.",
        "MAS ATÉ MESMO A LOUCURA TEM SEUS LIMITES. O CICLO LOGO RECOMEÇA,\nFORÇANDO ZACK A MERGULHAR MAIS UMA VEZ NA SUA PRÓPRIA ILUSÃO."
    ];
}
else if (global.historia == 111) {
    _nome = "SEM TER O QUE FAZER";
    global.devaneio = false;
    room_destino = Rm_variaveis;
    linhas = [
        "CARAMBA... VOCÊ REALMENTE NÃO TINHA O QUE FAZER, NÃO É MESMO?\nOU VOCÊ CONTOU TODAS, OU TRAPACEOU NOS ARQUIVOS, OU CHUTOU E ACERTOU.",
        "MAS DE QUALQUER FORMA... PARABÉNS!",
        "PARABÉNS! PARABÉNS! PARABUENS!",
        "AGORA VOCÊ VAI VOLTAR PARA O MENU PRINCIPAL... SUA RECOMPENSA POR POTENCIALMENTE TER TRAPACEADO... NOVAMENTE PARABUENS!"
    ];
}

else if (global.historia == 110) {
    _nome = "O DETETIVE COVARDE";
    global.devaneio = true;
    room_destino = Rm_Alem_dia_0;
    linhas = [
        "O ASSASSINO SEGUE LIVRE PELA NOITE, ENQUANTO O DETETIVE FOGE.",
        "DOMINÓ COM CERTEZA NÃO SERVIA PARA ISSO. NA SUA PRIMEIRA TENTATIVA... DESISTIU!",
        "DEIXOU O ASSASSINO À SOLTA APENAS PARA EVITAR A PRÓPRIA DOR.",
        "BOM... ACHO QUE SALVAR VIDAS REALMENTE NÃO É PRA TODOS, NÃO É MESMO?"
    ];
}
else if (global.historia == 100) {
    _nome = "O MAIOR DETETIVE DO MUNDO";
    global.devaneio = false;
    room_destino = Rm_variaveis;
    linhas = [
        "A VERDADE VEIO À TONA E A VERDADEIRA CULPADA FOI ENTREGUE À JUSTIÇA.\nDOMINÓ DEIXOU O LIMBO E RETORNOU AO MUNDO REAL COMO UM HERÓI.",
        "COM SUA REPUTAÇÃO CONSOLIDADA, ELE SE TORNOU O MAIOR DETETIVE DO MUNDO,\nRESOLVENDO INÚMEROS CASOS E GANHANDO FAMA INTERNACIONAL.",
        "NO ENTANTO, O PREÇO DESSA GLÓRIA FOI PAGO COM O SANGUE INOCENTE.\nAS VÍTIMAS QUE ELE ESCOLHEU NÃO SALVAR ASSOMBRAM SEUS SONHOS.",
        "UM FINAL DE SUCESSO E APLAUSOS, CONSTRUÍDO SOBRE UM ALICERCE DE EGOÍSMO.\nO CICLO SE FECHOU, MAS A CONSCIÊNCIA DE DOMINÓ JAMAIS TERÁ PAZ."
    ];
}
else if (global.historia == 108) {
    _nome = "CURVA MORTAL";
    global.devaneio = true;
    room_destino = Rm_Alem_dia_0;
    linhas = [
        "A INCOMPETÊNCIA NO VOLANTE COBROU UM PREÇO ALTO DEMAIS.\nO CARRO PERDEU O CONTROLE E CAIU NO PENHASCO, NÃO DEIXANDO SOBREVIVENTES.",
        "A VIAGEM TERMINOU ANTES MESMO DE COMEÇAR. SEM VÍTIMAS NA CASA,\nSEM MISTÉRIO, E ABSOLUTAMENTE NENHUM CASO PARA SER RESOLVIDO.",
        "DOMINÓ PERMANECEU NO ESCURO, ASSISTINDO A UM DESASTRE TÃO COMUM E TRÁGICO\nQUE ATÉ MESMO O PARADOXO FICOU SEM PALAVRAS."
    ];
}
else if (global.historia == 107) {
    _nome = "A QUEBRA DO CICLO";
    global.devaneio = false;
    room_destino = Rm_variaveis;
    linhas = [
        "DOMINÓ ABRIU MÃO DO SEU EGO E DA GLÓRIA PARA FAZER O QUE ERA CERTO.\nCOM A AJUDA DO PARADOXO, ELE REVERTEU O TEMPO E IMPEDIU O MASSACRE.",
        "OS CINCO JOVENS SOBREVIVERAM E VOLTARAM PARA CASA EM SEGURANÇA.\nCOMO CONSEQUÊNCIA, O INCIDENTE DEIXOU DE EXISTIR PARA SEMPRE.",
        "AO ATRAVESSAR A PORTA, O DETETIVE PERDEU SUAS MEMÓRIAS DO LIMBO E SEUS PODERES.\nELE VOLTOU A SER UM INVESTIGADOR MEDÍOCRE, DESCONHECIDO E SEM FAMA.",
        "MAS EMBORA O MUNDO NUNCA SAIBA DO SEU SACRIFÍCIO, ELE SALVOU AQUELAS VIDAS.\nO CICLO FOI QUEBRADO, E UM VERDADEIRO HERÓI DESCONHECIDO NASCEU NO ANONIMATO."
    ];
}
else if (global.historia == 106) {
    _nome = "QUASE LÁ";
    global.devaneio = false;
    room_destino = Rm_variaveis;
    linhas = [
        "A DEDUÇÃO FOI JUSTA. SAM TROUXE A FANTASIA E CAUSOU O APAGÃO.\nDOMINÓ O ENTREGOU COMO O GRANDE ARQUITETO DESSA NOITE DE HORROR.",
        "A SOCIEDADE ACEITOU O VEREDITO E O CASO FOI ENCERRADO COM SUCESSO.\nPORÉM, SAM JAMAIS TEVE A INTENÇÃO DE MACHUCAR NINGUÉM.",
        "DOMINÓ CONSTRUIU SEU SUCESSO EM CIMA DE UMA MEIA-VERDADE CONVENIENTE.\nO DETETIVE IGNOROU AS PEÇAS QUE NÃO SE ENCAIXAVAM NO SEU QUEBRA-CABEÇA.",
        "A FALTA DE UMA RESPOSTA COMPLETA DEIXOU UM VAZIO NA SUA CARREIRA.\nUM FINAL ACEITÁVEL, MAS QUE PASSA LONGE DA VERDADE ABSOLUTA."
    ];
}
else if (global.historia == 104) {
    _nome = "MUITO GRUDENTO";
    global.devaneio = false;
    room_destino = Rm_variaveis;
    linhas = [
        "BRENO FOI APONTADO COMO O GRANDE RESPONSÁVEL PELA TRAGÉDIA.\nA SUA AÇÃO PRECIPITADA AO DERRUBAR A COLA DE FATO SELOU O DESTINO DO GRUPO.",
        "O DETETIVE FOCOU NO ACIDENTE, IGNORANDO AS VERDADEIRAS INTENÇÕES.\nA JUSTIÇA FOI FEITA COM BASE NA NEGLIGÊNCIA, E NÃO NA MALÍCIA.",
        "DOMINÓ RECEBEU OS MÉRITOS, MAS A HISTÓRIA FICOU CHEIA DE FUROS LÓGICOS.\nCOMO ALGUÉM QUE APENAS DERRUBOU A COLA PODERIA ORQUESTRAR UM MASSACRE?",
        "O CASO FOI ARQUIVADO, MAS AS SOMBRAS DA DÚVIDA PERMANECERAM.\nUM RESULTADO MEDÍOCRE PARA UMA MENTE QUE PODERIA TER IDO ALÉM."
    ];
}
else if (global.historia == 105) {
    _nome = "VÍTIMA DO PÂNICO";
    global.devaneio = false;
    room_destino = Rm_variaveis;
    linhas = [
        "DOMINÓ CULPOU TIFFANY, A GAROTA QUE APENAS TENTOU BANCAR A HEROÍNA.\nELA AGIU NO ESCURO, MOVIDA PELO CHOQUE E PELO MAIS PURO PÂNICO.",
        "EMBORA TIVESSE SANGUE NAS MÃOS POR CONTA DO ACIDENTE, ELA NÃO ERA A VILÃ.\nO DETETIVE CONDENOU UMA VÍTIMA DO TERROR CIRCUNSTANCIAL.",
        "COM A CONCLUSÃO DO CASO, A VERDADEIRA MENTE POR TRÁS DA TRAGÉDIA ESCAPOU.\nO ASSASSINO REAL SAIU IMPUNE.",
        "O DETETIVE CONSEGUIU SEU VEREDITO, MAS A UM CUSTO TERRÍVEL.\nUMA DECISÃO CEGA QUE DESTRUIU O QUE RESTAVA DAQUELE GRUPO DE AMIGOS."
    ];
}
else if (global.historia == 109) {
    _nome = "O SONO DA BELEZA";
    global.devaneio = false;
    room_destino = Rm_variaveis;
    linhas = [
        "A PREGUIÇA FALOU MAIS ALTO E A VONTADE DE MUDAR O DESTINO FOI NULA.",
        "VOCÊ DORMIU PROFUNDAMENTE, IGNORANDO OS PROBLEMAS DO MUNDO LÁ FORA.",
        "O SILÊNCIO TOMOU CONTA. VOCÊ SIMPLESMENTE NÃO ACORDOU MAIS.",
        "SEM FORÇA DE VONTADE, NENHUMA HISTÓRIA É ESCRITA E NENHUM CASO É RESOLVIDO."
    ];
}

else if (global.historia == 103) {
    _nome = "O JULGAMENTO RIDÍCULO";
    global.devaneio = false;
    room_destino = Rm_variaveis;
    linhas = [
        "IGNORANDO TODOS OS AVISOS, DOMINÓ ACUSOU THEO, A PRIMEIRA VÍTIMA DO CASO.\nUM JOVEM QUE APENAS FUGIU EM DESESPERO E MORREU POR PURO INFORTÚNIO.",
        "O MUNDO COMPROU A NARRATIVA ABSURDA, POIS OS MORTOS NÃO PODEM SE DEFENDER.\nO DETETIVE MANIPULOU AS PROVAS PARA ENCAIXAR SUA TEORIA PATÉTICA.",
        "O CASO FOI DADO COMO ENCERRADO, MAS O ABSURDO DA SITUAÇÃO ERA EVIDENTE.\nATÉ MESMO O PARADOXO SENTIU NOJO DESSA CONCLUSÃO DEPLORÁVEL.",
        "NAS NOITES SILENCIOSAS, A INCOMPETÊNCIA ASSOMBRARÁ DOMINÓ PARA SEMPRE.\nELE VIVERÁ SABENDO QUE FOI O PIOR INVESTIGADOR QUE JÁ PISOU NA TERRA."
    ];
}
else if (global.historia == -100) {
    _nome = "SOBRE O JOGO";
    is_sobre = true;
    global.devaneio = false;
    room_destino = Rm_variaveis;
    linhas = [
        "DETECTIVE DOMINÓ FOI DESENVOLVIDO YUKISHIRODEV PARA NONE JAM 13 COM O TEMA: REAÇÃO EM CADEIA/EFEITO BORBOLETA, JOGO INSPIRADO EM DIVERSOS OUTROS BASEADOS NO MESMO TEMA, EM QUE VOCÊ PODE VOLTAR NO TEMPO PARA ALTERAR OS ACONTECIMENTOS.",
		"SEMANAS ANTES DA JAM COMEÇAR, TIVE A SORTE DE TER ZERADO 2 JOGOS NESSE ESTILO, OS QUAIS UTILIZEI DE PRINCIPAL INSPIRAÇÃO PARA O PROJETO, O JOGO NÃO POSSUI SAVES ENTÃO TEM QUE SER COMPLETADO EM UMA TACADA SÓ, MAS ELE É CURTO.",
		"UM AGRADECIMENTO ESPECIAL A VOCÊ POR EXPLORAR TODAS AS LINHAS DO TEMPO SEM ACESSAR PELO MENU (COMPLETAMENTE IMPOSSÍVEL).",
        "SERÁ QUE VOCÊ CONSEGUE DESCOBRIR QUEM É O VERDADEIRO ASSASSINO?"
    ];
}



if global.retorno_devaneio_continuar
	global.retornar=false
	
	
if (variable_global_exists("retornar") && global.retornar == true) {
    room_destino = Rm_variaveis;
}

if (!is_sobre) {
    var _lista = global.devaneio ? _devaneios : _finais;
    var _total = array_length(_lista);
    var _ordem = 1;

    for (var i = 0; i < _total; i++) {
        if (_lista[i] == global.historia) {
            _ordem = i + 1;
            break;
        }
    }

    var _prefixo = global.devaneio ? "DEVANEIO " : "FINAL ";
    titulo = _prefixo + string(_ordem) + "/" + string(_total) + " - " + _nome;
} else {
    titulo = _nome;
}

estado = "entrando";
alfa_fundo = 0;
alfa_geral = 0;

linha_atual = 0;
tempo_linha = 0;
alfas_linhas = array_create(array_length(linhas), 0);
y_offsets = array_create(array_length(linhas), 10);